personalBlog/blog/urls.py
from .feeds import LatestPostsFeed
from django.urls import path
from. import views


app_name = 'blog'
urlpatterns = [path('', views.post_list, name='post_list'),
               path('tag/<slug:tag_slug>', views.post_list,
                    name='post_list_by_tag_name'),
               path('feed/', LatestPostsFeed(), name='post_feed'),

               path('<slug:post>/', views.post_detail, name='post_detail'),
               path('<int:post_id>/share', views.post_share, name='post_share'), ]

personalBlog/personalBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', RedirectView.as_view(url='blog/')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),






]

personalBlog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedPostManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return(reverse('blog:post_detail', args=[self.slug]))


class ActiveCommentsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    mail = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    edited = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    objects = models.Manager()
    actives = ActiveCommentsManager()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment on the {self.post} by {self.name}"

personalBlog/blog/forms.py
from django import forms
from .models import Comment


class EmailForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(
        max_length=1000, required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'mail', 'body')

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'inline_field'
        self.fields['mail'].widget.attrs['class'] = 'inline_field'
        self.fields['body'].widget.attrs['class'] = 'block_field'

personalBlog/blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from .models import Post, Comment
from taggit.models import Tag
from django.db.models import Count
from.forms import EmailForm, CommentForm
# Create your views here.


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginate.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page, 'tag': tag})

# class PostListView(ListView):
#     model = 'Post'
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_detail(request, post):
    article = get_object_or_404(Post.published, slug=post)
    # calculating Similar Posts
    tag_ids = article.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=tag_ids).exclude(id=article.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')).order_by('-same_tags', '-publish')[:3]

    comments = article.comments.filter(post=article.id)
    new_comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_comment = form.save(commit=False)
            new_comment.post = article
            new_comment.save()
            form = CommentForm()
    else:
        form = CommentForm()

    return render(request, 'blog/post/detail.html', {'comments': comments, 'form': form, 'new_comment': new_comment, 'post': article, 'similar': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post.published, id=post_id)
    url = request.build_absolute_uri(post.get_absolute_url())
    sent = False
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = f"Article Recommendation From {cd['name']}"
            body = f"{cd['name']} recommends you to read this article: \n\" {post.title}\"\nurl: {url} \n Additional Comments: {cd['comment']}.\n Let him Know Your Thoughts at: {cd['email']}"
            send_mail(subject, body, 'moonem.ahmed@gmail.com', [cd['to']]
                      )
            sent = True
    else:
        form = EmailForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

personalBlog/blog/templates/blog/base.html
{%load blog_tags%}
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{%block title%}{%endblock%}</title>
  <link rel="stylesheet" href="{%static 'css/blog.css'%}" />
  <script src="https://kit.fontawesome.com/0eff1b1f1c.js" crossorigin="anonymous"></script>
</head>

<body>
  <div id="container">
    <div id="sidebar">
      <a href="{%url 'blog:post_list'%}">
        <h2>MnM Speaking</h2>
      </a>

      <p>{%total_posts%} pieces of my thoughts are available Here </p>
    </div>
  </div>
  <div id="content">
    {%block content%} {%endblock%}
  </div>
  <div id="besidebar">
    <p class="recents">
      <a href="{% url "blog:post_feed" %}">Subscribe RSS feed</a>
    </p>
    <div class="recents"> {%most_recent 5%}</div>

    <div class="commenteds"> {%most_commented_posts 5%}</div>
  </div>
</body>

</html>

personalBlog/blog/templates/blog/post/detail.html
{%extends 'blog/base.html'%}
{%load blog_tags%}

{%load static%} {% block title %}{{post.title}}
{%endblock%} {% block content %}
<div class="detail-post">
  <h1 class="post-title">{{post.title}}</h1>
  <h2 class="post-author">{{post.author}}</h2>

  <p class="post-date">{{post.publish}}</p>
  <p class="post-tag">Tags: {%for tag in post.tags.all%}
    <a href="{%url 'blog:post_list_by_tag_name' tag.slug%}"> {{tag.name}} </a>
    {%if not forloop.last%},{%endif%}
    {%endfor%} </p>
  <div id="share"><a href="{%url 'blog:post_share' post.id %}"><i class="fas fa-share-alt"></i></a></div>
  <p class="post-body">{{post.body|markdown}}</p>

</div>





<div class="comment_box">
  <form action="{%url 'blog:post_detail' post.slug%}" method="POST">
    {%csrf_token%}

    {%if form.non_field.errors%}
    <div class="errors">
      <ul>
        {%for error in form.non_field.errors%}
        <li>{{error}}</li>
        {%endfor%}
      </ul>
    </div>
    {%endif%}

    {%for hidden_field in form.hidden_fields%}

    {%if hidden_field.errors%}
    <div class="errors">
      <ul>
        {%for error in hidden_field.errors.errors%}
        <li>(Hidden Field {{hidden_field.name}}) {{error}}</li>
        {%endfor%}
      </ul>
    </div>
    {%endif%}
    {{hidden_field}}
    {%endfor%}
    <div class="inlineinputs">
      <div id="comment_name">
        <p class="label"> {{form.name.label_tag}}
        </p>
        {{form.name}}
      </div>
      <div id="comment_mail">
        <p class="label"> {{form.mail.label_tag}}
        </p>
        {{form.mail}}
      </div>
    </div>

    <div id="comment_body">
      {{form.body}}
    </div>
    <input type="submit" id='post_comment' value='POST'>
  </form>
</div>
<div class="comment_lists">
  {%for comment in comments%}
  <div class="single_comment">
    <h3 class="post-author">{{comment.name}}</h3>
    <p class="post-date">{{comment.created}}</p>
    <p class="post-body">{{comment.body}}</p>
  </div>
  {%endfor%}
</div>
<h2 id="related_declare">Similar Posts</h2>

<div class="similar">
  {%for s in similar%}
  <div class="singlesim"><a href="{{s.get_absolute_url}}">
      <h1>{{s.title}}</h1>
    </a>
    <p class="publish-info">Published {{s.publish}} by {{s.author}}</p>
    <p class="trailer">{{s.body|truncatewords:30}}</p>
  </div>
  {%endfor%}
</div>

{% endblock %}

personalBlog/blog/templates/blog/post/list.html
{%extends 'blog/base.html'%}
{%load blog_tags%}
{%load static%} {%block title%} MNM
Speaking{%endblock%} {% block content %} {%if tag%}
<h2 class="tag_exist">Posts Tagged #{{tag}}</h2>
{%endif%}{% for post in posts %}

<div class="singlepost">
  <a href="{{post.get_absolute_url}}">
    <h1>{{post.title}}</h1>
  </a>
  <p class="publish-info">Published {{post.publish}} by {{post.author}}</p>
  <p class="trailer">{{post.body|markdown|truncatewords_html:30}}</p>
</div>
{% endfor %}
<div class="pagination">
  <form action="{%url 'blog:post_list'%}" method="GET">
    {% if posts.has_previous %}

    <button name='page' value={{posts.previous_page_number}}>Previous</button>
    {% endif %}

    page {{posts.number}} of {{posts.paginator.num_pages}} {% if posts.has_next %}
    <button name='page' value={{posts.next_page_number}}>Next</button>
    {% endif %}
  </form>
</div>
{% endblock %}

personalBlog/blog/templates/blog/post/most_commented.html
<h3>Most Discussed Posts</h3>
<ul>
    {%for cp in commented_post%}
    <li>
        <a href="{{ cp.get_absolute_url}}">
            {{cp.title}}
        </a>
    </li>
    {%endfor%}
</ul>

personalBlog/blog/templates/blog/post/recent_posts.html
<h3>Most Recent Posts</h3>
<ul>
    {%for recent in recent_posts%}
    <li>
        <a href="{{ recent.get_absolute_url}}">
            {{recent.title}}
        </a>
    </li>
    {%endfor%}
</ul>

personalBlog/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{%load static%}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<p class='post-title'>
    {{ post.title }} <span>was successfully sent to</span> {{form.cleaned_data.to }}.
</p>
{% else %}
<h1 class='post-title'> <span>Share</span> {{ post.title }}</h1>

<div class="shareform">
    <form method="post">
        {% csrf_token %}


        {%if form.non_field.errors%}
        <div class="errors">
            <ul>
                {%for error in form.non_field.errors%}
                <li>{{error}}</li>
                {%endfor%}
            </ul>
        </div>
        {%endif%}

        {%for hidden_field in form.hidden_fields%}

        {%if hidden_field.errors%}
        <div class="errors">
            <ul>
                {%for error in hidden_field.errors.errors%}
                <li>(Hidden Field {{hidden_field.name}}) {{error}}</li>
                {%endfor%}
            </ul>
        </div>
        {%endif%}
        {{hidden_field}}
        {%endfor%}
        <div id="share_name">
            <p class="label"> {{form.name.label_tag}}
            </p>
            {{form.name}}
        </div>
        <div class="inlineinputshare">

            <div id="share_email">
                <p class="label"> {{form.email.label_tag}}
                </p>
                {{form.email}}
            </div>

            <div id="share_to_email">
                <p class="label"> {{form.to.label_tag}}
                </p>
                {{form.to}}
            </div>
        </div>

        <div id="share_comment">
            <p class="label"> {{form.comment.label_tag}}
            </p>
            {{form.comment}}
        </div>
        <button type="submit">Send</button>
    </form>
</div>
{% endif %}




{% endblock %}